name: test-partner

on:
  workflow_dispatch:
    inputs:
      data1:
        required: true
      data2:
        required: true
      data3:
        required: true
    
jobs:
  set-up:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-array.outputs.matrix }}
    steps:
      - name: Extract added yml and image file
        id: set-array
        run: |
          echo "::notice ::data1=${{ github.event.inputs.data1 }}"
          echo "::notice ::data2=${{ github.event.inputs.data2 }}"
          echo "::notice ::data3=${{ github.event.inputs.data3 }}"
          echo "::notice \
          ::data1=${{ github.event.inputs.data1 }}¥n data2=${{ github.event.inputs.data2 }}¥n data3=${{ github.event.inputs.data3 }}\n"
          file="${{ github.event.inputs.data1 }}"
          files+=($file)
          file="${{ github.event.inputs.data2 }}"
          files+=($file)
          file="${{ github.event.inputs.data3 }}"
          files+=($file)
          echo ${files[@]}
          output=$(printf "%s\n" "${files[@]}" | jq -R . | jq -s -c .)
          echo "matrix=${files[@]}">>$GITHUB_OUTPUT
          echo "YML_FILE_PATHS=${files[@]}" >> $GITHUB_OUTPUT
      - name: echo files
        id: echo-array
        run: |
          for i in ${{ steps.set-array.outputs.matrix }}
          do
            echo "$i\n"
          done
          for i in ${{ steps.set-array.outputs.YML_FILE_PATHS }}
          do
            echo "$i\n"
          done
  wait:
    runs-on: ubuntu-latest
    needs: set-up
    steps:
    - name: Manual trigger needed
      run: echo "Please manually trigger the next job when ready."
  Loggin:
    runs-on: ubuntu-latest
    needs: wait
    steps:
    - name: watch loggin
      run: |
        echo "::warning data1: ${{ github.event.inputs.data1 }}::Missing semicolon"
        echo "::warning data2: ${{ github.event.inputs.data2 }}::Missing semicolon"
        echo "::warning data3: ${{ github.event.inputs.data3 }}::Missing semicolon"
