name: test-partner

on:
  workflow_dispatch:
    inputs:
      data1:
        required: true
      data2:
        required: true
      data3:
        required: true
    

jobs:
  setup-partner:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Extract added yml and image file
        id: added-files
        run: |
          files+=("${{ github.event.inputs.data1 }}")
          files+=("${{ github.event.inputs.data2 }}")
          files+=("${{ github.event.inputs.data3 }}")
          echo $files[@]
          IFS=' ' read -r -a file_array << files[@]
          echo $file_array
          output=$(printf '%s\n' "${file_array[@]}" | jq -R . | jq -s .)
          echo $output
          echo "matrix=$output" >> $GITHUB_OUTPUT

  setup-multi-partner:
    needs: setup-partner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJSON(needs.setup-partner.outputs.matrix) }}
    steps:
      - name: Set scripts path
        id: echo-files
        run: echo ${{ matrix.value }}
