name: test-partner

on:
  workflow_dispatch:
    inputs:
      data1:
        required: true
      data2:
        required: true
      data3:
        required: true
    
jobs:
  set-up:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-array.outputs.matrix }}
    steps:
      - name: Extract added yml and image file
        id: set-array
        run: |
          file="${{ github.event.inputs.data1 }}"
          files+=($file)
          file="${{ github.event.inputs.data2 }}"
          files+=($file)
          file="${{ github.event.inputs.data3 }}"
          files+=($file)
          echo ${files[@]}
          output=$(printf "%s\n" "${files[@]}" | jq -R . | jq -s -c .)
          echo "matrix=$output">>$GITHUB_OUTPUT

  setup-multi-partner:
    needs: set-array
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.set-array.outputs.matrix) }}
    steps:
      - name: Set scripts path
        id: echo-files
        run: echo ${{ matrix.item }}
