name: Go Action

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
    branches:
      - main
    
jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Extract added yml and image file
        id: set-array
        run: |
          echo "input to"
