name: Go Action

on:
  workflow_call:
    inputs:
      to:
        required: true
        type: string
      from:
        required: true
        type: string
    
jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Extract added yml and image file
        id: set-array
        run: |
          echo "input to:" + ${{ github.event.inputs.to }}
          echo "input from:" + ${{ github.event.inputs.from }}
