name: test-partner

on:
  workflow_dispatch:
    inputs:
      data1:
        required: true
      data2:
        required: true
      data3:
        required: true
    

jobs:
  set-array:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.array-json }}
    steps:
      - name: Extract added yml and image file
        id: added-files
        run: |
          files+=("${{ github.event.inputs.data1 }}")
          files+=("${{ github.event.inputs.data2 }}")
          files+=("${{ github.event.inputs.data3 }}")
          output=$(printf '%s\n' ${files[@]} | jq -R . | jq -s -c .)
          echo ${output}
          echo "array-json=$output" >> $GITHUB_OUTPUT

  setup-multi-partner:
    needs: set-array
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.set-array.outputs.matrix) }}
    steps:
      - name: Set scripts path
        id: echo-files
        run: echo ${{ matrix.item }}
