name: Test Matrix

on:
  workflow_dispatch:
    inputs:
      data1:
        required: false
      data2:
        required: false
      data3:
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
      - run: echo '::set-output name=value::["a", "b", "c"]'
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: echo "${{ matrix.value }}"
